// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitnessManagement.Models;

public partial class Attendance
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int? SubscriptionId { get; set; }

    public int? ServiceId { get; set; }

    public DateTime? CheckInTime { get; set; }

    public int? CheckedBy { get; set; }

    public virtual User CheckedByNavigation { get; set; }

    public virtual User Client { get; set; }

    public virtual Service Service { get; set; }

    public virtual Subscription Subscription { get; set; }
}