// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitnessManagement.Models;

public partial class PurchaseRequest
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TypeId { get; set; }

    public string Status { get; set; }

    public bool? Paid { get; set; }

    public DateTime? RquestedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public virtual User Client { get; set; }

    public virtual SubscriptionType Type { get; set; }
}