// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitnessManagement.Models;

public partial class Subscription
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TypeId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int? RemainingVisits { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual User Client { get; set; }

    public virtual SubscriptionType Type { get; set; }
}