// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitnessManagement.Models;

public partial class SubscriptionTypeService
{
    public int Id { get; set; }

    public int SubscriptionTypeId { get; set; }

    public int ServiceId { get; set; }

    public virtual Service Service { get; set; }

    public virtual SubscriptionType SubscriptionType { get; set; }
}