// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FitnessManagement.Models;

public partial class SubscriptionType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int DurationDays { get; set; }

    public decimal Price { get; set; }

    public int? DailyVisitLimit { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<PurchaseRequest> PurchaseRequests { get; set; } = new List<PurchaseRequest>();

    public virtual ICollection<SubscriptionTypeService> SubscriptionTypeServices { get; set; } = new List<SubscriptionTypeService>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}